@url = https://friendly-halibut-px9prpv9qvrf7jv9-8080.app.github.dev/alunos


GET {{url}}

###
GET {{url}}/4

###
POST {{url}}
Content-Type: application/json

{
    "id": 1,
    "nome": "Felipe Rosse Cavalcante",
    "idade": 20
}

###
PUT {{url}}/1
Content-Type: application/json

{
    "nome": "Nome Alterado",
    "idade": 200
}


###
DELETE {{url}}/1